version: '3.8'
services:
  node-api:
    build:
      context: .
      dockerfile: ./dockerfiles/node.Dockerfile
    ports:
      - "3000:3000"
    networks:
      - "PWA"
  apache-server:
    build:
      context: .
      dockerfile: ./dockerfiles/apache.Dockerfile
    ports:
      - "80:80"
    networks:
      - "PWA"

networks:
  PWA:
